name: Auto Tweet Generate

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2 
        with:
          python-version: "3.8.2"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytz
          pip install datetime

      - name: Run auto-generate.py
        run: |
          python auto-generate.py

      - name: Commit and Push
        run: |
          git config user.name "Murayu0225"
          git config user.email "murayu@assistant-app.com"
          git config --global pull.rebase false
          git add .
          git commit -m "Tweet Created!"
          git pull --allow-unrelated-histories origin data
          git push origin data
