name: Pull Request Labeler

on:
  - pull_request
jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - name: Label for Transifex and auto tweet
        if: github.actor == 'transifex-integration[bot]' && 'github-actions[bot]' && !endsWith(github.event.pull_request.title, '[manual sync]')
        uses: actions/labeler@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
